### ISSUE TITLE
Восстановление монет

### ISSUE THREAD

**Issue by Xyu201099** [greenaddress/garecovery#41]
Сделайте, пожалуйста, в кошельке грин доступную функцию по восстановлению монет. Это же сколько клиентов теряете!!!
Ну вот завис перевод ни туда ни сюда, почему-то во время перевода решили, что комиссию нужно увеличить. И висят эти деньги неизвестно где. Как восстановить эти монетки?????

**Comment by jgriffiths** [comment]
Hi @Xyu201099 

If I understand correctly, your recovery transactions are not confirming because the current network fees are too high? If you import the private keys into a wallet like Electrum, you should be able to use child-pays-for-parent to increase their fee and get them to confirm, otherwise you will need to wait until the mempool becomes less busy and fees drop (you might need to broadcast the transactions again when fees are lower).

We have enabled CSV for the wallets now which means that you can set the fee at recovery time instead of having a fixed fee like the nlocktime.zip transactions. And soon you will be able to recover those from the wallet directly by just spending them when they expire. But since your old UTXOs are not CSV this does not help your case now I'm afraid.
 
If you have any other problems or I've misunderstood your issue, please contact support at https://help.blockstream.com/. I will close this issue as we don't offer support through github.

**Comment by Xyu201099** [comment]
Блин, да просто можно сделать функцию отмена транзакции?
Мне просто нужно отменить транзакцию и вернуть деньги

**Comment by jgriffiths** [comment]
Bitcoin transactions can not be cancelled once they are broadcast to the network. As long as someone has a transaction in thier mempool, they can broadcast it to miners at any time in the future unless the coins are spent with another transaction that the network accepts first (using e.g. RBF).

RBF is not available for recovery transactions unfortunately, the network difficulty should fall soon and hopefully the mempool will clear enough to allow your transactions to confirm.
